server:
  port: 8002
spring:
  application:
    name: hardware_manage_system_service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graduation_user_manage?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/,http://localhost:8000/eureka/
  instance:
    #prefer-ip-address: true  #ip地址作为注册名
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #向注册中注册服务id
    lease-renewal-interval-in-seconds: 3 #发送心跳的间隔
    lease-expiration-duration-in-seconds: 6 #续约到期时间,告诉eureka在6秒内如果没有收到心跳，则将自己从服务器剔除